txt = input("Enter text :")
txt_0 = txt.count('0')
txt_1 = txt.count('1')
txt_2 = txt.count('2')
txt_3 = txt.count('3')
txt_4 = txt.count('4')
txt_5 = txt.count('5')
txt_6 = txt.count('6')
txt_7 = txt.count('7')
txt_8 = txt.count('8')
txt_9 = txt.count('9')
print(txt_0 + txt_1 + txt_2 + txt_3 + txt_4 + txt_5 + txt_6 + txt_7 + txt_8 + txt_9 > 0)